### PR TITLE
Enable remote_bitbang support by default

### LINKED ISSUE #133: Enable remote_bitbang by default on next release?
Hello Espressif,

I'm connecting to the ESP32S2 using the newly released "Glasgow" explorer board:

https://www.crowdsupply.com/1bitsquared/glasgow

Which supports that `remote_bitbang` probe interfacing via a [so-called FPGA "applet"](https://github.com/GlasgowEmbedded/glasgow/blob/master/software/glasgow/applet/interface/jtag_openocd/__init__.py):

```shell
$ glasgow run jtag-openocd --pin-tck 0 --pin-tms 3 --pin-tdi 2 --pin-tdo 1 -V 3.3 tcp:localhost:2222
I: g.device.hardware: building bitstream ID b97acf8ca32a08beb46d6713ecdb8b98
Warning: Wire top.$flatten\i2c_target.\bus.$verilog_initial_trigger has an unprocessed 'init' attribute.
Warning: Wire top.$flatten\multiplexer.\U$$0.\U$$2.$verilog_initial_trigger has an unprocessed 'init' attribute.
Warning: Wire top.$flatten\multiplexer.\U$$0.\U$$2.\bus.$verilog_initial_trigger has an unprocessed 'init' attribute.
Warning: Wire top.$verilog_initial_trigger has an unprocessed 'init' attribute.
I: g.cli: running handler for applet 'jtag-openocd'
I: g.applet.interface.jtag_openocd: port(s) A, B voltage set to 3.3 V
I: g.applet.interface.jtag_openocd: socket: listening at tcp:localhost:2222
```

Unfortunately, to my surprise, I found that `remote_bitbang` is disabled by default on my OpenOCD-ESP32 build?

```
$ which openocd
/Users/romanvg/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200709/openocd-esp32/bin/openocd
$ openocd --version
Open On-Chip Debugger  v0.10.0-esp32-20200709 (2020-07-09-08:54)
Licensed under GNU GPL v2

$ openocd -c 'interface remote_bitbang; remote_bitbang_port 2222'
Open On-Chip Debugger  v0.10.0-esp32-20200709 (2020-07-09-08:54)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Error: The specified debug interface was not found (remote_bitbang)
The following debug interfaces are available:
1: ftdi
2: usb_blaster
3: ft232r
4: jlink
5: vsllink
6: ulink
7: hla
8: osbdm
9: opendous
10: aice
11: xds110
```

Could you please enable it back on future builds? Thanks in advance!

### PR DESCRIPTION
**Pull request by brainstorm**
Fixes #133 

https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/hw-reference/esp32s2/user-guide-saola-1-v1.2.html

First commit fails because this board does not seem to have JTAG_USB support since it's fronted by an FTDI IC instead (UART), resulting in:

```
$ ../src/openocd -f board/esp32s2-saola-1.cfg
Open On-Chip Debugger  v0.10.0-esp32-20201202 (2021-01-02-21:22)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Info : USB protocol set for esp remote
Info : VID set to 0x303a and PID to 0x1002
Warn : Transport "jtag" was already selected
Info : FreeRTOS creation
Info : FreeRTOS creation
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections

Assertion failed: (jtag_trst == 0), function jtag_checks, file src/jtag/core.c, line 343.
Abort trap: 6
```

Instead the following file in `openocd/tcl/interface`...:

```shell
$ cat tcl/interface/jtag_esp_remote.cfg
interface jtag_esp_remote

jtag_esp_remote_protocol usb
jtag_esp_remote_vid_pid 0x303a 0x1002

#jtag_esp_remote_protocol tcp
#jtag_esp_remote_set_port 5555
#jtag_esp_remote_set_address "127.0.0.1"
```

... Needs to be edited accordingly:

```shell
interface jtag_esp_remote

#jtag_esp_remote_protocol usb
#jtag_esp_remote_vid_pid 0x303a 0x1002

jtag_esp_remote_protocol tcp
jtag_esp_remote_set_port 5555
jtag_esp_remote_set_address "127.0.0.1"
```

Perhaps this should be documented accordingly somewhere in espressif documentation?

If connecting with a remote JTAG bitbanging Glasgow board like so:

image

And running the following Glasgow applet command:

```
$ glasgow run jtag-openocd --port A --pin-tck 0 --pin-tms 3 --pin-tdi 2 --pin-tdo 1 -V 3.3 tcp:localhost:5555
I: g.cli: running handler for applet 'jtag-openocd'
I: g.applet.interface.jtag_openocd: port(s) A voltage set to 3.3 V
I: g.applet.interface.jtag_openocd: socket: listening at tcp:localhost:5555
```

Plus the corresponding OpenOCD command on another terminal:

```
$ ../src/openocd -f board/esp32s2-saola-1.cfg
Open On-Chip Debugger  v0.10.0-esp32-20201202 (2021-01-02-21:22)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Info : TCP protocol set for esp remote
Info : Set server port to 5555
Info : Set server address to 127.0.0.1
Warn : Transport "jtag" was already selected
Info : FreeRTOS creation
Info : FreeRTOS creation
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Connection to 127.0.0.1 : 5555 succeed
Info : This adapter doesn't support configurable speed
```

Which should be fixed in VSCode ESP-IDF extension (see issue https://github.com/espressif/vscode-esp-idf-extension/issues/259), ideally ;)

### CODE REVIEW

**Comment by brainstorm** [comment]
Predictably though, the `jtag_esp_remote` protocol is not compatible with the OpenOCD "native" `remote_bitbang` protocol and so any attempt at GDB fails miserably:

```
(gdb) target remote :5555
Remote debugging using :5555
Ignoring packet error, continuing...
warning: unrecognized item "timeout" in "qSupported" response
Ignoring packet error, continuing...
Remote replied unexpectedly to 'vMustReplyEmpty': timeout
(gdb) 
```

Garbling the OpenOCD side with bad commands (I guess?):

```
$ ../src/openocd -f board/esp32s2-saola-1.cfg
Open On-Chip Debugger  v0.10.0-esp32-20201202 (2021-01-02-21:22)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Info : TCP protocol set for esp remote
Info : Set server port to 5555
Info : Set server address to 127.0.0.1
Warn : Transport "jtag" was already selected
Info : FreeRTOS creation
Info : FreeRTOS creation
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Connection to 127.0.0.1 : 5555 succeed
Info : This adapter doesn't support configurable speed
Info : TAP esp32.cpu0 has invalid IDCODE (0xcccccccc)
Info : TAP esp32.cpu1 has invalid IDCODE (0x66666666)
Info : JTAG tap: auto0.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto1.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto2.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto3.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto4.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto5.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto6.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto7.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto8.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto9.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto10.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto11.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto12.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto13.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto14.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto15.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto16.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto17.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Info : JTAG tap: auto18.tap tap/device found: 0x33333333 (mfg: 0x199 (Centon Electronics), part: 0x3333, ver: 0x3)
Warn : Unexpected idcode after end of chain: 610 0x33333333
Error: double-check your JTAG setup (interface, speed, ...)
Error: Trying to use configured scan chain anyway...
Error: esp32.cpu0: IR capture error; saw 0x0c not 0x01
Warn : Bypassing JTAG setup events due to errors
Info : Listening on port 3333 for gdb connections
shutdown command invoked
Error: Failed to clear OCDDCR_ENABLEOCD!
Error: Failed to clear OCDDCR_ENABLEOCD!
```

**Comment by brainstorm** [comment]
After recompiling `remote_bitbang`, I'm almost there:

```
$ ../src/openocd -f board/esp32s2-saola-1.cfg
Open On-Chip Debugger  v0.10.0-esp32-20201202-2-g7e342cad (2021-01-02-23:47)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Warn : Transport "jtag" was already selected
Info : FreeRTOS creation
Info : FreeRTOS creation
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Initializing remote_bitbang driver
Info : Connecting to localhost:5555
Info : remote_bitbang driver initialized
Info : This adapter doesn't support configurable speed
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0xffffffff (mfg: 0x7ff (<invalid>), part: 0xffff, ver: 0xf)
Warn : JTAG tap: esp32.cpu1       UNEXPECTED: 0xffffffff (mfg: 0x7ff (<invalid>), part: 0xffff, ver: 0xf)
Error: JTAG tap: esp32.cpu1  expected 1 of 1: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Error: Trying to use configured scan chain anyway...
Error: esp32.cpu1: IR capture error; saw 0x1f not 0x01
Warn : Bypassing JTAG setup events due to errors
Info : Listening on port 3333 for gdb connections
```

**Comment by brainstorm** [comment]
Fortunately in this PR, the "classic" OpenOCD `remote_bitbang` is re-enabled and things seem to work between Glasgow and ESP32S3 Saola-1 dev board:

```
$ ../src/openocd -f board/esp32s2-saola-1.cfg
Open On-Chip Debugger  v0.10.0-esp32-20201202-2-g7e342cad (2021-01-02-23:47)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Warn : Transport "jtag" was already selected
Info : FreeRTOS creation
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Initializing remote_bitbang driver
Info : Connecting to localhost:5555
Info : remote_bitbang driver initialized
Info : This adapter doesn't support configurable speed
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s2: Core was reset.
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
Warn : No symbols for FreeRTOS!
```

**Comment by igrr** [comment]
Hi @brainstorm, thanks for the PR.
We can definitely enable `remote_bitbang` in the next release.

Regarding tcl/board/esp32s2-saola-1.cfg — i'm not sure about adding this file. Normally we add board-specific TCL files only when the board has a built-in JTAG interface. In other cases, if the board doesn't contain the JTAG interface, you can run OpenOCD specifying a pair of config files: one for the target, and one for the interface. This way every user can choose which interface to use. You can probably agree that "remote_bitbang" as the default for Saola is no better than any other interface that can be connected externally (JLink, FT2232H, etc).

We can add a trivial config file for remote_bitbang interface, so that you can run OpenOCD like this:

```
openocd -f target/esp32s2.cfg -f interface/remote_bitbang.cfg
```

Would this work for you?

**Comment by brainstorm** [comment]
You are totally right, Igor, I see your point.

Your suggestion would work for me as well, so I'll get rid of the Saola config and put in place what you propose.

I'll fix it tonight, thanks for the speedy review!

**Comment by brainstorm** [comment]
@igrr Actually instead of your command:

> 
> ```
> openocd -f target/esp32s2.cfg -f interface/remote_bitbang.cfg
> ```

It would be with the argument flipped like this:

```
$ openocd -f interface/remote_bitbang.cfg -f target/esp32s2.cfg
Open On-Chip Debugger  v0.10.0-esp32-20201202-2-g7e342cad (2021-01-02-23:47)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
Warn : Transport "jtag" was already selected
Info : FreeRTOS creation
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Initializing remote_bitbang driver
Info : Connecting to localhost:5555
Info : remote_bitbang driver initialized
Info : This adapter doesn't support configurable speed
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s2: Core was reset.
Info : Listening on port 3333 for gdb connections
```

Otherwise I get the following error:

```shell
$ openocd -f target/esp32s2.cfg -f interface/remote_bitbang.cfg
Open On-Chip Debugger  v0.10.0-esp32-20201202-2-g7e342cad (2021-01-02-23:47)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Error: Debug adapter doesn't support any transports?
target/esp32s2.cfg:2: Error:
in procedure 'script'
at file "embedded:startup.tcl", line 26
at file "target/esp32s2.cfg", line 2
```

So ready to merge as-is now... would you document this somewhere in official docs? I don't want other people to go through this again :P

Thanks!

**Comment by igrr** [comment]
Thanks @brainstorm. Regarding documenting this, I've added a task in the internal issue tracker. Once a new OpenOCD release is made and IDF is updated to use it, we'll mention this in the docs.

May I ask you to combine the 6 commits in your branch into one commit, e.g. "interface: enable remote_bitbang by default and add cfg file"? If you are unsure how, you can also leave it as is and I will do it for you, keeping your authorship.

**Comment by brainstorm** [comment]
Sure @igrr rebased, reworded, squashed and pushed right now. Eager to see the new release so I don't have to fiddle with it across updates anymore ;)

**Comment by brainstorm** [comment]
@igrr happy to write that up in the docs too if that helps speeding up the merge? Just point me a repo or `.md` file and I'll try to do the rest ;)

**Pull request closed without merging**
