### PR TITLE
Add support for detection of 32-256MB flash chips to the esp stub (OCD-623)

### PR DESCRIPTION
**Pull request by johnboiles**
Currently the ESP stub does not work for flash chips > 32MB (except for possibly one mysterious 32MB chip with size designator `0x39` 🤷). This PR adds support for 32MB, 64MB, 128MB, and 256MB chips. This has been verified as the correct size numbering scheme for Winbond, GigaDevice, and Micron flash chips (see discussion in [this PR](https://github.com/espressif/esp-idf/pull/9381)). 

Similar PRs across the Espressif ecosystem:
* https://github.com/espressif/esptool/pull/769
* https://github.com/espressif/esp-idf/pull/9381
* https://github.com/espressif/esp-idf/pull/9566

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I've tested this on an ESP32-S3R8 with a 512Mbit (64MB) flash chip.

### CODE REVIEW

**Comment by gerekon** [comment]
Hi @johnboiles 

Thanks for the work. But I see that you PR includes code section hex files updates for ESP32-C3 only.
We will pick C-file changes up and generate hex files correctly.

**Comment by johnboiles** [comment]
If you're able to come up with a change to these files based on this c code please let me know. But I could imagine the compiler could be possibly turn this switch statement into a look up table and put it in `.data` 🤷 

My process was:
* Checkout esp-idf `036bd3eb26`, update submodules
* `./install.sh` `source export.sh`
* cd `../openocd-esp32/contrib/loaders/flash/esp`
* `for dir in esp32 esp32c3 esp32s2 esp32s3; do pushd $dir; make; popd; done`
* cd `../esp-idf`
* Checkout esp-idf `06b31d487b`, update submodules
* `./install.sh` `source export.sh`
* cd `../openocd-esp32/contrib/loaders/flash/esp/esp32c2`
* make

**Comment by johnboiles** [comment]
I was curious so I tried to understand whether the code was reading the `.data` section of the binary using `xtensa-esp32s3-elf-objdump -lSd build/stub_flasher.elf` but I haven't quite been able to follow it. I could imagine that last `l32i.n` possibly loading from the `.data` section.

image

**Comment by erhankur** [comment]
@johnboiles We picked your work as 2 commits (eeb0d52ebb3e470a3fa259100f7811af87f68d54 and 6cd81a6687b6e8200582aa649b28f41246506cba) into the master branch. Please check them and create an issue if you find something. Now, I can close this PR.  Thanks for your contribution.

**Pull request closed without merging**
